jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run script
        env:
          API_KEY: ${{ secrets.IMGUR_API_KEY }}
        run: node your-script.js